name: blockfrost_api
version: 1.0.0
description: OpenAPI API client
environment:
    # sdk: '>=2.7.0 <3.0.0'
    sdk: ">=2.12.0 <3.0.0"
dependencies:
    # dio: ^3.0.9
    dio: ^4.0.0
    # built_value: ">=7.1.0 <8.0.4"
    built_value: ^8.0.4
    built_collection: ^5.0.0
    # built_collection: ">=4.3.2 <5.0.0"
dev_dependencies:
    # built_value_generator: ">=7.1.0 <8.0.4"
    built_value_generator: ^8.0.4
    # build_runner: ^1.7.1
    build_runner: ^1.12.2
    # test: ">=1.3.0 <1.16.0"
    test: ^1.16.8
